/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include "unistd.h"

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 138
#define YY_END_OF_BUFFER 139
static yyconst short int yy_accept[372] =
    {   0,
      133,  133,    0,    0,    0,    0,   45,   45,    0,    0,
      139,  137,   59,   60,   97,  137,   63,   93,   94,   82,
       83,   91,   89,   90,  101,   92,  133,  133,   81,   80,
       85,   88,   84,  136,   98,   99,   96,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,   78,   95,   79,  137,   25,   27,   26,   29,
       28,   30,   58,   33,   31,   49,   58,   58,   56,   57,
       45,   58,   45,   45,   50,   58,   51,   47,   47,   47,
       47,   47,   47,   58,   23,    3,    4,    1,    2,   23,
       23,   23,   23,   23,   23,   23,   23,   59,   77,    0,

        0,  131,    0,   70,   75,   71,   68,   66,   64,   67,
      134,  134,   65,  100,  133,   62,  132,   69,  133,  133,
      136,  135,   87,   74,   86,   73,  136,  136,  136,  136,
      136,  136,  118,  136,  136,  136,  136,  136,  136,  136,
      107,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,   72,   76,    0,   25,   24,   29,   33,
        0,    0,   43,    0,   55,   45,   32,   45,   45,   47,
       46,    0,    0,   52,   44,    0,   48,   53,   47,   47,
       47,   47,   38,   47,   47,   54,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,  131,    0,  134,  134,  133,  135,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  117,  136,  136,  104,
      136,  136,  103,  136,  136,  136,  136,  136,  136,  136,
      136,  102,  136,   61,    0,   43,    0,   45,   46,    0,
       44,    0,   41,   47,   47,   47,   47,   47,   47,   11,
        0,    0,    0,    0,    0,   14,    7,    0,   22,   13,
        6,   10,    0,    0,   12,  134,  136,  136,  114,  136,
      136,  136,  108,  136,  136,  136,  106,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,   47,   39,
       47,   47,   47,   47,   47,    0,   15,   18,   17,   16,

        0,    9,    0,  111,  116,  124,  136,  136,  112,  136,
      136,  136,  136,  136,  136,  136,  121,  136,  136,  136,
      136,  136,  109,   47,   47,   40,   37,   47,   47,    5,
        0,    0,    0,    8,  136,  136,  122,  136,  127,  136,
      136,  136,  136,  128,  120,  105,  113,  136,   36,   42,
       47,   35,   20,   19,   21,  136,  115,  136,  136,  126,
      129,  136,  123,   34,  119,  110,  136,  136,  125,  130,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    8,   11,
       12,   13,   14,    8,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    8,    8,   25,   25,   25,   25,   25,   25,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,   30,   26,    8,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   60,    8,    8,    8,
       61,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,   62,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    2,    1,    1,    4,    1,    4,    4,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[385] =
    {   0,
        0,    0,   60,   61,   62,   63,   76,    0,  137,  185,
      808,  809,   65,  809,  784,  144,  809,  783,  132,  809,
      809,  782,  129,  138,   52,  146,  148,  157,  809,  809,
      781,  780,  779,  785,  809,  809,  777,  132,  149,  162,
      163,  168,  166,  169,  174,  196,  178,  199,  189,  205,
      207,  210,  809,  137,  809,  739,    0,  809,  781,    0,
      809,  809,  809,  147,  809,  809,  240,  787,  809,  809,
      181,  779,  217,  233,  252,  772,  771,  777,  221,  229,
      240,  241,  211,  734,  809,  199,  809,  809,  809,  757,
      217,  222,  231,  739,  754,  218,  228,  279,  809,  285,

      291,  809,  297,  809,  809,  809,  809,  809,  809,  809,
      271,  286,  809,  809,  277,  809,  809,  809,  288,  292,
      772,  310,  809,  809,  809,  809,  285,  296,  298,  299,
      293,  300,  771,  301,  304,  302,  305,  307,  306,  311,
      770,  316,  317,  318,  322,  324,  332,  333,  338,  341,
      342,  344,  343,  809,  809,  724,    0,  809,    0,  364,
      371,  383,  809,  394,  809,  357,  809,  360,  385,  768,
      407,  405,  433,  443,  446,  449,  809,  809,  345,  354,
      365,  371,  382,  377,  386,  809,  411,  749,  738,  421,
      729,  734,  748,  732,  735,  723,  729,  725,  728,  740,

      477,  483,  489,  400,  402,  409,    0,  393,  437,  396,
      438,  414,  444,  446,  450,  453,  755,  443,  456,  754,
      477,  480,  753,  466,  481,  482,  483,  484,  486,  487,
      490,  752,  488,  809,  525,  537,  543,  490,    0,  549,
      554,  557,  751,  497,  494,  503,  531,  525,  532,  809,
      717,  718,  714,  713,  727,  809,  809,  719,  809,  809,
      809,  809,  722,  711,  809,  543,  538,  548,  742,  552,
      554,  556,  741,  558,  563,  559,  740,  564,  567,  560,
      568,  578,  579,  572,  574,  570,  586,  581,  580,  739,
      576,  590,  594,  582,  584,  704,  809,  718,  717,  809,

      702,  809,  715,  733,  732,  731,  588,  589,  730,  598,
      605,  606,  612,  613,  618,  619,  729,  620,  621,  622,
      623,  624,  715,  625,  627,  706,  702,  629,  631,  809,
      651,  648,  659,  809,  630,  633,  673,  635,  672,  638,
      639,  641,  643,  671,  669,  668,  663,  648,  657,  508,
      651,  504,  809,  809,  809,  656,  502,  655,  659,  500,
      498,  661,  496,  421,  256,  250,  662,  666,  180,  175,
      809,  700,  704,  708,  712,   68,  716,  720,  724,   64,
      728,  732,  736,  740
    } ;

static yyconst short int yy_def[385] =
    {   0,
      371,    1,  372,  372,  373,  373,  371,    7,  374,  374,
      371,  371,  371,  371,  371,  375,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  376,  376,  371,  371,
      371,  371,  371,  376,  371,  371,  371,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  371,  371,  371,  371,  377,  371,  371,  378,
      371,  371,  371,  371,  371,  371,  379,  371,  371,  371,
      371,  371,  380,  380,  381,  371,  371,  380,  380,  380,
      380,  380,  380,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  375,

      375,  371,  382,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  376,
      376,  376,  371,  371,  371,  371,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  371,  371,  371,  377,  371,  378,  371,
      379,  379,  371,  383,  371,  371,  371,  371,  380,  380,
      380,  381,  381,  381,  381,  384,  371,  371,  380,  380,
      380,  380,  380,  380,  380,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      375,  375,  382,  371,  371,  371,  122,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  371,  379,  379,  383,  371,  171,  381,
      381,  384,  380,  380,  380,  380,  380,  380,  380,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  380,  380,
      380,  380,  380,  380,  380,  371,  371,  371,  371,  371,

      371,  371,  371,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  380,  380,  380,  380,  380,  380,  371,
      371,  371,  371,  371,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  380,  380,
      380,  380,  371,  371,  371,  376,  376,  376,  376,  376,
      376,  376,  376,  380,  376,  376,  376,  376,  376,  376,
        0,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371
    } ;

static yyconst short int yy_nxt[872] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   12,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   34,   35,   12,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   34,
       34,   34,   34,   47,   34,   48,   34,   49,   50,   34,
       34,   51,   52,   34,   34,   34,   53,   54,   55,   12,
       12,   56,   58,   58,   61,   61,   98,  170,   98,  115,
      115,  121,   59,   59,   62,   62,   63,   64,   65,   64,
       66,   67,   63,   63,   63,   68,   69,   70,   63,   63,
       63,   71,   72,   73,   74,   63,   63,   75,   76,   77,

       78,   78,   63,   63,   63,   63,   79,   78,   78,   80,
       81,   78,   78,   78,   82,   78,   78,   78,   78,   78,
       78,   83,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   63,   84,   63,   63,   63,   63,   86,   87,
       86,  105,  108,   88,  100,  100,  100,  371,  160,  102,
      160,  109,  110,  111,  106,  112,  112,   89,  116,  154,
      113,  114,  117,  119,  371,  120,  120,   90,  118,   91,
       92,  103,  119,  127,  120,  120,   93,  371,  371,   94,
       95,  371,   96,  371,  371,   97,   86,   87,   86,  371,
      371,   88,  129,  371,  155,  371,  128,  132,  166,  166,

      187,  122,  187,  130,  371,   89,  131,  133,  140,  134,
      137,  371,  144,  139,  371,   90,  138,   91,   92,  135,
      371,  136,  371,  148,   93,  371,  371,   94,   95,  145,
       96,  141,  168,   97,  169,  169,  371,  152,  142,  143,
      161,  161,  161,  149,  371,  163,  146,  153,  168,  147,
      169,  169,  172,  172,  172,  371,  371,  150,  185,  151,
      191,  189,  197,  180,  190,  371,  193,  164,  198,  179,
      171,  371,  192,  194,  174,  175,  183,  199,  200,  176,
       98,  181,   98,  182,  184,  100,  100,  100,  204,  204,
      102,  100,  100,  100,  115,  115,  102,  101,  101,  100,

      371,  205,  202,  112,  112,  206,  206,  119,  371,  120,
      120,  371,  103,  371,  371,  371,  371,  371,  103,  371,
      371,  371,  371,  208,  203,  371,  371,  207,  207,  211,
      209,  371,  371,  371,  207,  213,  212,  371,  215,  371,
      207,  207,  207,  207,  207,  207,  210,  371,  371,  214,
      218,  216,  217,  371,  224,  219,  371,  371,  371,  371,
      371,  221,  225,  227,  220,  160,  222,  160,  226,  371,
      223,  161,  161,  161,  166,  166,  163,  238,  238,  230,
      371,  233,  228,  161,  161,  161,  371,  243,  163,  244,
      231,  232,  371,  229,  162,  162,  161,  371,  164,  236,

      168,  371,  169,  169,  246,  172,  172,  172,  371,  248,
      164,  371,  187,  245,  187,  247,  249,  204,  204,  266,
      266,  237,  371,  267,  239,  239,  206,  206,  175,  371,
      269,  239,  176,  172,  172,  172,  371,  239,  239,  239,
      239,  239,  239,  172,  172,  172,  172,  172,  172,  173,
      173,  172,  371,  371,  172,  252,  175,  253,  371,  371,
      176,  371,  254,  271,  255,  371,  175,  268,  371,  175,
      176,  371,  241,  176,  272,  276,  242,  100,  100,  100,
      273,  371,  102,  100,  100,  100,  270,  275,  102,  101,
      101,  100,  371,  274,  202,  371,  371,  371,  371,  371,

      277,  371,  371,  371,  103,  371,  280,  238,  238,  371,
      103,  371,  371,  371,  279,  371,  203,  371,  371,  371,
      285,  278,  287,  371,  283,  161,  161,  161,  290,  288,
      163,  282,  281,  291,  284,  289,  286,  161,  161,  161,
      371,  292,  163,  162,  162,  161,  371,  371,  236,  172,
      172,  172,  164,  371,  172,  172,  172,  173,  173,  172,
      266,  266,  172,  371,  164,  293,  294,  371,  295,  371,
      237,  371,  175,  371,  371,  371,  176,  175,  371,  371,
      241,  176,  371,  371,  242,  371,  304,  371,  305,  371,
      314,  371,  307,  371,  371,  371,  371,  371,  315,  371,

      306,  371,  321,  371,  371,  371,  308,  309,  311,  371,
      310,  312,  316,  371,  313,  323,  322,  318,  320,  319,
      371,  371,  317,  324,  325,  326,  329,  371,  371,  327,
      336,  335,  328,  371,  371,  371,  371,  371,  371,  371,
      371,  337,  371,  338,  371,  371,  371,  340,  371,  341,
      371,  343,  344,  371,  371,  339,  371,  346,  371,  349,
      347,  352,  351,  371,  345,  348,  371,  342,  359,  350,
      371,  371,  371,  360,  371,  361,  371,  371,  371,  358,
      356,  371,  357,  371,  371,  364,  371,  371,  371,  363,
      365,  367,  362,  355,  354,  368,  369,  353,  366,  370,

       57,   57,   57,   57,   60,   60,   60,   60,   85,   85,
       85,   85,  101,  101,  101,  101,  157,  371,  157,  157,
      159,  371,  159,  159,  162,  162,  162,  162,  173,  173,
      371,  173,  201,  201,  201,  201,  235,  235,  235,  235,
      240,  240,  240,  240,  371,  371,  371,  371,  371,  334,
      333,  332,  331,  330,  371,  371,  371,  371,  303,  302,
      301,  300,  299,  298,  297,  296,  371,  371,  371,  371,
      371,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  251,  250,  371,  234,  371,  371,  371,  196,  195,
      188,  186,  371,  178,  177,  167,  165,  158,  156,  126,

      371,  125,  124,  123,  107,  104,   99,  371,   11,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371
    } ;

static yyconst short int yy_chk[872] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,   13,  380,   13,   25,
       25,  376,    3,    4,    5,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    9,    9,
        9,   19,   23,    9,   16,   16,   16,   38,   64,   16,
       64,   23,   24,   24,   19,   24,   24,    9,   26,   54,
       24,   24,   26,   27,   39,   27,   27,    9,   26,    9,
        9,   16,   28,   38,   28,   28,    9,   40,   41,    9,
        9,   43,    9,   42,   44,    9,   10,   10,   10,   45,
      370,   10,   40,   47,   54,  369,   39,   41,   71,   71,

       86,   27,   86,   40,   49,   10,   40,   41,   45,   42,
       43,   46,   47,   44,   48,   10,   43,   10,   10,   42,
       50,   42,   51,   49,   10,   52,   83,   10,   10,   48,
       10,   46,   73,   10,   73,   73,   79,   51,   46,   46,
       67,   67,   67,   50,   80,   67,   48,   52,   74,   48,
       74,   74,   75,   75,   75,   81,   82,   50,   83,   50,
       92,   91,   96,   80,   91,  366,   93,   67,   96,   79,
       73,  365,   92,   93,   75,   75,   82,   97,   97,   75,
       98,   81,   98,   81,   82,  100,  100,  100,  111,  111,
      100,  101,  101,  101,  115,  115,  101,  103,  103,  103,

      127,  112,  103,  112,  112,  119,  119,  120,  131,  120,
      120,  128,  100,  129,  130,  132,  134,  136,  101,  135,
      137,  139,  138,  127,  103,  122,  140,  122,  122,  130,
      128,  142,  143,  144,  122,  132,  131,  145,  135,  146,
      122,  122,  122,  122,  122,  122,  129,  147,  148,  134,
      138,  136,  137,  149,  145,  139,  150,  151,  153,  152,
      179,  142,  146,  147,  140,  160,  143,  160,  146,  180,
      144,  161,  161,  161,  166,  166,  161,  168,  168,  150,
      181,  153,  148,  162,  162,  162,  182,  179,  162,  180,
      151,  152,  184,  149,  164,  164,  164,  183,  161,  164,

      169,  185,  169,  169,  182,  172,  172,  172,  208,  184,
      162,  210,  187,  181,  187,  183,  185,  204,  204,  205,
      205,  164,  171,  208,  171,  171,  206,  206,  172,  212,
      210,  171,  172,  173,  173,  173,  364,  171,  171,  171,
      171,  171,  171,  174,  174,  174,  175,  175,  175,  176,
      176,  176,  209,  211,  176,  190,  173,  190,  218,  213,
      173,  214,  190,  212,  190,  215,  174,  209,  216,  175,
      174,  219,  176,  175,  213,  218,  176,  201,  201,  201,
      214,  224,  201,  202,  202,  202,  211,  216,  202,  203,
      203,  203,  221,  215,  203,  222,  225,  226,  227,  228,

      219,  229,  230,  233,  201,  231,  224,  238,  238,  245,
      202,  363,  244,  361,  222,  360,  203,  357,  246,  352,
      229,  221,  231,  350,  227,  235,  235,  235,  245,  233,
      235,  226,  225,  246,  228,  244,  230,  236,  236,  236,
      248,  246,  236,  237,  237,  237,  247,  249,  237,  240,
      240,  240,  235,  267,  241,  241,  241,  242,  242,  242,
      266,  266,  242,  268,  236,  247,  248,  270,  249,  271,
      237,  272,  240,  274,  276,  280,  240,  241,  275,  278,
      242,  241,  279,  281,  242,  286,  267,  284,  268,  285,
      280,  291,  271,  282,  283,  289,  288,  294,  281,  295,

      270,  287,  286,  307,  308,  292,  272,  274,  276,  293,
      275,  278,  282,  310,  279,  288,  287,  283,  285,  284,
      311,  312,  282,  289,  291,  292,  295,  313,  314,  293,
      308,  307,  294,  315,  316,  318,  319,  320,  321,  322,
      324,  310,  325,  311,  328,  335,  329,  313,  336,  314,
      338,  316,  318,  340,  341,  312,  342,  320,  343,  324,
      321,  329,  328,  348,  319,  322,  351,  315,  340,  325,
      358,  356,  349,  341,  359,  342,  362,  367,  347,  338,
      335,  368,  336,  346,  345,  351,  344,  339,  337,  348,
      356,  359,  343,  333,  332,  362,  367,  331,  358,  368,

      372,  372,  372,  372,  373,  373,  373,  373,  374,  374,
      374,  374,  375,  375,  375,  375,  377,  327,  377,  377,
      378,  326,  378,  378,  379,  379,  379,  379,  381,  381,
      323,  381,  382,  382,  382,  382,  383,  383,  383,  383,
      384,  384,  384,  384,  317,  309,  306,  305,  304,  303,
      301,  299,  298,  296,  290,  277,  273,  269,  264,  263,
      258,  255,  254,  253,  252,  251,  243,  232,  223,  220,
      217,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  189,  188,  170,  156,  141,  133,  121,   95,   94,
       90,   84,   78,   77,   76,   72,   68,   59,   56,   37,

       34,   33,   32,   31,   22,   18,   15,   11,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "stack.lex"
#define INITIAL 0
#line 2 "stack.lex"
/*=========================================================================
C-libraries and Token definitions
=========================================================================*/
#include <string.h> /* for strdup */
/*#include <stdlib.h> */ /* for atoi */
#include "token.h"
#include "stack_tab.h" /* for token definitions and yylval */
#include "lex_proto.h"
#include "sym_table.h"
#include "asm_streamer.h"

#define YY_INPUT(buf,result,max_size) { \
	int c = '*', n, d; \
	for ( n = 0; n < max_size && \
		     (c = pp_getc( p_config )) != EOF && c != '\n'; ++n ) \
		buf[n] = (char)(c); \
	if ( c == '\n' ) { \
        while((d = pp_getc( p_config )) == '\r' || d == '\n') { if( d=='\n' ) p_config->line++; }\
        if( d == EOF) {\
            pp_close( p_config);\
		    p_config = lp_pop_config();\
        } else {\
            pp_seek( p_config, -1, SEEK_CUR);\
		    buf[n++] = (char) c; \
        }\
	} \
	if ( c == EOF && pp_error(  p_config ) ) {\
		/*printf( "input in flex scanner failed\n" );*/ \
	}\
	if(p_config->show_assembly) {\
		as_info(_RECAST(uchar *, buf));	\
	}\
	if ( c == EOF) {\
		pp_close( p_config);\
		p_config = lp_pop_config();\
	}\
	result = n; \
	/*buf[n]=0;\
	printf("%s\n", buf);*/\
	if(result<=0) result=YY_NULL; \
}


/*=========================================================================
TOKEN Definitions
=========================================================================*/
#define BLOCK_COMMENT_SECTION 1

#define LINE_COMMENT_SECTION 2

#define PREPROCESSOR_SECTION 3

#define ASSEMBLER_SECTION 4

/*NUMBER [0-9]*  */
/*=========================================================================
REGULAR EXPRESSIONS defining the tokens for the Simple language
=========================================================================*/
#line 740 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 61 "stack.lex"

#line 893 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 809 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 63 "stack.lex"
{ BEGIN(PREPROCESSOR_SECTION); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "stack.lex"
{ BEGIN(LINE_COMMENT_SECTION); } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "stack.lex"
{ /* eat up whitespace */ } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "stack.lex"
{ p_config->line++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "stack.lex"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "stack.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "stack.lex"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "stack.lex"

	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "stack.lex"

	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "stack.lex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "stack.lex"

	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "stack.lex"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "stack.lex"

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "stack.lex"

	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "stack.lex"

	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "stack.lex"

	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "stack.lex"

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "stack.lex"

	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "stack.lex"

	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "stack.lex"

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "stack.lex"

	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "stack.lex"

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK


case 24:
YY_RULE_SETUP
#line 89 "stack.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "stack.lex"
{ /* eat comment in chunks */ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "stack.lex"
{ /* eat the lone star */ }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 92 "stack.lex"
{ p_config->line++; }
	YY_BREAK


case 28:
YY_RULE_SETUP
#line 96 "stack.lex"
{ p_config->line++; BEGIN(INITIAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "stack.lex"
// eat comment in chunks
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "stack.lex"
// eat the lone star
	YY_BREAK


case 31:
YY_RULE_SETUP
#line 102 "stack.lex"
{ p_config->line++; lp_flush_token(); if(_lex_state != LEX_STATE_INVALID) BEGIN(INITIAL); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "stack.lex"
{ lp_flush_token(); if(_lex_state != LEX_STATE_INVALID) BEGIN(LINE_COMMENT_SECTION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "stack.lex"
{ /*lp_preprocessor_state(LEX_STATE_INCLUDE);*/ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_PRAGMA); 	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_DEFINE);  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_IFDEF); 	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_IF); 		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_ELSE); 	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_ENDIF); 	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 112 "stack.lex"
{ BEGIN(ASSEMBLER_SECTION); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "stack.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 114 "stack.lex"
{ 
		uchar buffer[4096];
		uint16 length;
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, yytext + 1, strlen(yytext) - 2);
		length = lp_unescape(buffer, buffer);
		lp_process_token(buffer, length);
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 122 "stack.lex"
{ 
		uchar buffer[4096];
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, yytext + 1, strlen(yytext) - 2);
		lp_process_token(buffer, strlen((const char *)buffer));
	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 128 "stack.lex"
{
		lp_process_token(_RECAST(uchar *, yytext), strlen(_RECAST(const char *, yytext)));
	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 131 "stack.lex"
{ 				
		char buffer[1024];	
		memset(buffer, 0, sizeof(buffer));
		sprintf(buffer, "%i", lp_hex2integer(yytext + 2));
		lp_process_token((uchar *)buffer, strlen((const char *)buffer));
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 137 "stack.lex"
{
		lp_process_token(_RECAST(uchar *, yytext), strlen(yytext));
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "stack.lex"
{ lp_push_opcode(LEX_OP_EQ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "stack.lex"
{ lp_push_opcode(LEX_OP_NEG); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "stack.lex"
{ lp_push_opcode(LEX_OP_LT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "stack.lex"
{ lp_push_opcode(LEX_OP_GT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "stack.lex"
{ lp_push_opcode(LEX_OP_LTEQ); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 145 "stack.lex"
{ lp_push_opcode(LEX_OP_GTEQ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 146 "stack.lex"
{ lp_push_opcode(LEX_OP_OR); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 147 "stack.lex"
{ lp_push_opcode(LEX_OP_AND); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 148 "stack.lex"
{ /* ignore */ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 149 "stack.lex"
{ /* ignore */ }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 153 "stack.lex"
{ /* eat up whitespace */ } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 154 "stack.lex"
{ p_config->line++; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 155 "stack.lex"
{ /* eat up byte order mark */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 157 "stack.lex"
{ BEGIN(BLOCK_COMMENT_SECTION); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 158 "stack.lex"
{ BEGIN(PREPROCESSOR_SECTION); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 160 "stack.lex"
{ return S_ADDEQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 161 "stack.lex"
{ return S_SUBEQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 162 "stack.lex"
{ return S_ADDADD; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 163 "stack.lex"
{ return S_SUBSUB; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 164 "stack.lex"
{ return S_MULEQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 165 "stack.lex"
{ return S_DIVEQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 166 "stack.lex"
{ return S_MODEQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 167 "stack.lex"
{ return S_ANDEQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 168 "stack.lex"
{ return S_OREQ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 169 "stack.lex"
{ return S_XOREQ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 171 "stack.lex"
{ return T_EQ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 172 "stack.lex"
{ return T_AND; }	//type and
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 173 "stack.lex"
{ return T_OR; }	//type or
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 174 "stack.lex"
{ return T_NE; }	//type not equal
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 175 "stack.lex"
{ return L_CL; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 176 "stack.lex"
{ return R_CL; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 177 "stack.lex"
{ return EOS; } 	//semicolon (end of statement)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 178 "stack.lex"
{ return EOC; } 	//colon (end of label)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 179 "stack.lex"
{ return L_BR; }	//left bracket
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 180 "stack.lex"
{ return R_BR; } 	//right bracket
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 181 "stack.lex"
{ return T_GT; }	//type greater than
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 182 "stack.lex"
{ return T_LT; }	//type less than
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 183 "stack.lex"
{ return T_GTEQ; }	//type greater than
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 184 "stack.lex"
{ return T_LTEQ; }	//type less than
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 185 "stack.lex"
{ return S_EQ; }	//type equal
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 186 "stack.lex"
{ return S_ADD; } 	
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 187 "stack.lex"
{ return S_SUB; } 	
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 188 "stack.lex"
{ return S_MUL; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 189 "stack.lex"
{ return S_DIV; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 190 "stack.lex"
{ return S_MOD; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 191 "stack.lex"
{ return S_AND; } 	
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 192 "stack.lex"
{ return S_OR; } 	
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 193 "stack.lex"
{ return S_XOR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 194 "stack.lex"
{ return S_NOT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 195 "stack.lex"
{ return L_SB; }	//left square bracket
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 196 "stack.lex"
{ return R_SB; } 	//right square bracket
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 197 "stack.lex"
{ return S_RNEXT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 198 "stack.lex"
{ return S_PDOT; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 200 "stack.lex"
{ return P_VAR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 201 "stack.lex"
{ return P_NEW; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 202 "stack.lex"
{ return P_HEX; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 203 "stack.lex"
{ return P_SIZEOF; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 205 "stack.lex"
{ return P_GOTO; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 206 "stack.lex"
{ return P_IF; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 207 "stack.lex"
{ return P_ELSE; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 208 "stack.lex"
{ return P_WHILE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 209 "stack.lex"
{ return P_FUNCTION; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 210 "stack.lex"
{ return P_ALIAS; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 211 "stack.lex"
{ return P_EVENT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 212 "stack.lex"
{ return P_SWITCH; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 213 "stack.lex"
{ return P_CASE; } 
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 214 "stack.lex"
{ return P_DEFAULT; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 215 "stack.lex"
{ return P_BREAK; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 216 "stack.lex"
{ return P_FOR; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 217 "stack.lex"
{ return P_DO; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 218 "stack.lex"
{ return P_CONTINUE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 219 "stack.lex"
{ return P_RETURN; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 220 "stack.lex"
{ return P_PROTO; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 221 "stack.lex"
{ return P_EXTERN; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 222 "stack.lex"
{ return P_SYSCALL; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 224 "stack.lex"
{ return P_CLASS; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 225 "stack.lex"
{ return P_INTERFACE; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 226 "stack.lex"
{ return P_PACKAGE; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 227 "stack.lex"
{ return P_IMPORT; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 228 "stack.lex"
{ return P_PUBLIC; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 229 "stack.lex"
{ return P_PRIVATE; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 230 "stack.lex"
{ return P_PROTECTED; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 232 "stack.lex"
{ 
	char buffer[4096];
	uint16 length;
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext + 1, strlen(yytext) - 2);
	memset(yylval.string, 0, sizeof(yylval.string));
	length = lp_unescape(_RECAST(uchar *, yylval.bytes.value), _RECAST(uchar *, buffer));
	yylval.bytes.length = length;
	return CONSTANT; 
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 243 "stack.lex"
{ BEGIN(LINE_COMMENT_SECTION); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 245 "stack.lex"
{ 			
	char buffer[256];	
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext, strlen(yytext));
	memcpy((uchar *)(yylval.bytes.value), buffer, strlen(buffer) + 1);
	yylval.bytes.length = strlen(buffer);
	if(strstr(buffer, ".") != NULL) return NUMERIC;
	return CONSTANT; 
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 255 "stack.lex"
{ 				
	char buffer[256];	
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext, strlen(yytext));
	memcpy((uchar *)(yylval.bytes.value), buffer, strlen(buffer) + 1);
	yylval.bytes.length = strlen(buffer);
	if(strstr(buffer, ".") != NULL) return N_NUMERIC;
	return N_CONSTANT;
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 265 "stack.lex"
{ 				
	char buffer[1024];	
	memset(buffer, 0, 256);
	sprintf(buffer, "%i", lp_hex2integer(yytext + 2));
	memcpy((uchar *)(yylval.bytes.value), buffer, strlen(buffer) + 1);
	yylval.bytes.length = strlen(buffer);
	return CONSTANT; 
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 274 "stack.lex"
{	
	pp_const * pconst = NULL;
	symrec * var = NULL;
	char buffer[4096];
	uint32 offset = 0;
	pconst = lp_select(_RECAST(uchar *, yytext));			/* select from preprocessor constants */
	if(pconst == NULL) {
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, yytext, strlen(yytext));
		memcpy((uchar *)(yylval.string), buffer, strlen(buffer) + 1);
		return VARIABLE;
	} else {							/* preprocessor constant found */
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, pconst->value, pconst->length);
		memcpy(_RECAST(uchar *, yylval.bytes.value), buffer, pconst->length);
		yylval.bytes.length = pconst->length;
		return CONSTANT;
	}	
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 294 "stack.lex"
{ return(yytext[0]); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 295 "stack.lex"
ECHO;
	YY_BREAK
#line 1745 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLOCK_COMMENT_SECTION):
case YY_STATE_EOF(LINE_COMMENT_SECTION):
case YY_STATE_EOF(PREPROCESSOR_SECTION):
case YY_STATE_EOF(ASSEMBLER_SECTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 371);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 295 "stack.lex"


int yywrap(void) { return -1; }

void yyinit(void) { 
	YY_FLUSH_BUFFER;
	BEGIN(INITIAL);	
}

/************************** End Scanner File *****************************/



