/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include "unistd.h"

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
static yyconst short int yy_accept[357] =
    {   0,
      126,  126,    0,    0,    0,    0,   45,   45,    0,    0,
      132,  130,   59,   60,  130,  130,   63,   90,  130,   79,
       80,   88,   86,   87,   94,   89,  126,  126,   78,   77,
       82,   85,   81,  129,   91,   92,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,   75,  130,   76,  130,   25,   27,   26,   29,   28,
       30,   58,   33,   31,   49,   58,   58,   56,   57,   58,
       45,   45,   50,   58,   51,   47,   47,   47,   47,   47,
       47,   58,   23,    3,    4,    1,    2,   23,   23,   23,
       23,   23,   23,   23,   23,   59,   74,    0,    0,  124,

        0,   70,   72,   68,   66,   64,   67,  127,   65,   93,
       62,  125,   69,  126,  129,  128,   84,   71,   83,  129,
      129,  129,  129,  129,  129,  111,  129,  129,  129,  129,
      129,  129,  129,  100,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,   73,    0,   25,   24,
       29,   33,    0,    0,   43,    0,   55,   32,   45,   47,
       46,    0,    0,   52,   44,    0,   48,   53,   47,   47,
       47,   47,   38,   47,   47,   54,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  124,    0,  128,  129,  129,  129,  129,  129,  129,

      129,  129,  129,  110,  129,  129,   97,  129,  129,   96,
      129,  129,  129,  129,  129,  129,  129,  129,   95,  129,
       61,    0,   43,    0,   46,    0,   44,    0,   41,   47,
       47,   47,   47,   47,   47,   11,    0,    0,    0,    0,
        0,   14,    7,    0,   22,   13,    6,   10,    0,    0,
       12,  129,  129,  107,  129,  129,  129,  101,  129,  129,
      129,   99,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,   47,   39,   47,   47,   47,   47,   47,
        0,   15,   18,   17,   16,    0,    9,    0,  104,  109,
      117,  129,  129,  105,  129,  129,  129,  129,  129,  129,

      129,  114,  129,  129,  129,  129,  129,  102,   47,   47,
       40,   37,   47,   47,    5,    0,    0,    0,    8,  129,
      129,  115,  129,  120,  129,  129,  129,  129,  121,  113,
       98,  106,  129,   36,   42,   47,   35,   20,   19,   21,
      129,  108,  129,  129,  119,  122,  129,  116,   34,  112,
      103,  129,  129,  118,  123,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    8,   11,
       12,   13,   14,    8,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    8,    8,   25,   25,   25,   25,   25,   25,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,    8,   26,    8,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   59,    8,    8,    8,
       60,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,   61,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    2,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[370] =
    {   0,
        0,    0,   59,   60,   61,   62,   75,    0,  135,  182,
      590,  591,   64,  591,  566,  142,  591,  565,  577,  591,
      591,  563,  126,  135,  591,  134,  142,   51,  591,  591,
      562,  561,  560,    0,  591,  591,  541,  534,  111,  128,
      122,  132,  536,  545,  155,  544,  141,  543,  154,  546,
      538,  591,  517,  591,  514,    0,  591,  555,    0,  591,
      591,  591,  162,  591,  591,  198,  561,  591,  591,  553,
      175,  191,  215,  546,  545,    0,  519,  532,  138,  170,
      518,  507,  591,  218,  591,  591,  591,  530,  185,  169,
      198,  512,  527,  152,  185,  240,  591,  244,  250,  591,

      256,  591,  591,  591,  591,  591,  591,  218,  591,  591,
      591,  591,  591,  230,    0,  236,  591,  591,  591,  522,
      525,  510,  527,  513,  520,    0,  506,  519,  503,  504,
      507,  500,  495,    0,  502,  497,  493,  512,  235,  512,
      493,  486,  502,  491,  491,  499,  591,  476,    0,  591,
        0,  261,  274,  280,  591,  286,  591,  591,  272,    0,
      285,  297,  304,  310,  321,  334,  591,  591,  493,  499,
      485,  499,  498,  498,  499,  591,  291,  495,  484,  305,
      475,  480,  494,  478,  481,  469,  475,  471,  474,  486,
      341,  349,  358,    0,  486,  485,  480,  465,  463,  481,

      476,  466,  474,    0,  475,  462,    0,  461,  470,    0,
      463,  451,  452,  459,  449,  464,  448,  464,    0,  454,
      591,  364,  370,  377,    0,  386,  392,  398,    0,  456,
      459,  193,  458,  450,  454,  591,  441,  442,  438,  437,
      451,  591,  591,  443,  591,  591,  591,  591,  446,  435,
      591,  433,  440,    0,  431,  440,  427,    0,  427,  428,
      425,    0,  426,  425,  441,  427,  230,  410,  397,  381,
      392,  393,  387,  376,    0,  370,  382,  380,  363,  370,
      362,  591,  375,  374,  591,  359,  591,  372,    0,    0,
        0,  360,  361,    0,  354,  358,  342,  355,  349,  335,

      350,    0,  349,  332,  339,  331,  322,    0,  323,  314,
        0,    0,  321,  323,  591,  287,  285,  296,  591,  279,
      278,    0,  282,    0,  279,  267,  263,  247,    0,    0,
        0,    0,  253,    0,    0,  251,    0,  591,  591,  591,
      226,    0,  198,  179,    0,    0,  153,    0,    0,    0,
        0,  135,  113,    0,    0,  591,  426,  430,  434,  438,
       67,  442,  446,  450,   63,  454,  458,  462,  466
    } ;

static yyconst short int yy_def[370] =
    {   0,
      356,    1,  357,  357,  358,  358,  356,    7,  359,  359,
      356,  356,  356,  356,  356,  360,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  361,  361,  356,  356,
      356,  356,  356,  361,  356,  356,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  356,  356,  356,  356,  362,  356,  356,  363,  356,
      356,  356,  356,  356,  356,  364,  356,  356,  356,  356,
      365,  365,  366,  356,  356,  365,  365,  365,  365,  365,
      365,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  360,  360,  356,

      367,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  361,  361,  361,  356,  356,  356,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  356,  356,  362,  356,
      363,  356,  364,  364,  356,  368,  356,  356,  365,  365,
      365,  366,  366,  366,  366,  369,  356,  356,  365,  365,
      365,  365,  365,  365,  365,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      360,  360,  367,  116,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      356,  364,  364,  368,  161,  366,  366,  369,  365,  365,
      365,  365,  365,  365,  365,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  365,  365,  365,  365,  365,  365,  365,
      356,  356,  356,  356,  356,  356,  356,  356,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  365,  365,
      365,  365,  365,  365,  356,  356,  356,  356,  356,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  365,  365,  365,  365,  356,  356,  356,
      361,  361,  361,  361,  361,  361,  361,  361,  365,  361,
      361,  361,  361,  361,  361,    0,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356
    } ;

static yyconst short int yy_nxt[653] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   12,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   34,   35,   12,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   34,   34,
       34,   34,   46,   34,   47,   34,   48,   49,   34,   34,
       50,   51,   34,   34,   34,   52,   53,   54,   12,   12,
       55,   57,   57,   60,   60,   96,  160,   96,  114,  114,
      115,   58,   58,   61,   61,   62,   63,   64,   63,   65,
       66,   62,   62,   62,   67,   68,   69,   62,   62,   62,
       62,   70,   71,   72,   62,   62,   73,   74,   75,   76,

       76,   62,   62,   62,   77,   76,   76,   78,   79,   76,
       76,   76,   80,   76,   76,   76,   76,   76,   76,   81,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       62,   82,   62,   62,   62,   62,   84,   85,   84,  105,
      122,   86,   98,   98,   98,  355,  111,  100,  106,  107,
      112,  123,  108,  108,  124,   87,  113,  109,  110,  114,
      114,  125,  127,  152,   88,  152,   89,   90,  354,  101,
      138,  126,  128,   91,  129,  130,   92,   93,  171,   94,
      172,  131,   95,   84,   85,   84,  353,  139,   86,  134,
      140,  142,  159,  159,  116,  187,  135,  136,  153,  153,

      153,  188,   87,  155,  173,  143,  181,  144,  159,  159,
      352,   88,  174,   89,   90,  162,  162,  162,  182,  177,
       91,  177,  276,   92,   93,  156,   94,  161,  179,   95,
      277,  180,  183,  189,  190,  108,  108,  164,  165,  184,
      351,   96,  166,   96,   98,   98,   98,  114,  114,  100,
       98,   98,   98,  194,  194,  100,   99,   99,   98,  350,
      194,  192,  152,  301,  152,  194,  194,  194,  194,  194,
      194,  101,  212,  302,  153,  153,  153,  101,  213,  155,
      153,  153,  153,  193,  349,  155,  154,  154,  153,  159,
      159,  223,  177,  348,  177,  347,  346,  162,  162,  162,

      345,  156,  225,  225,  162,  162,  162,  156,  344,  225,
      162,  162,  162,  224,  225,  225,  225,  225,  225,  225,
      165,  162,  162,  162,  166,  343,  342,  165,  341,  340,
      339,  166,  338,  165,  163,  163,  162,  166,  238,  162,
      239,   98,   98,   98,  165,  240,  100,  241,  166,   98,
       98,   98,  337,  336,  100,  335,  334,  227,   99,   99,
       98,  228,  333,  192,  153,  153,  153,  332,  101,  155,
      153,  153,  153,  331,  330,  155,  101,  154,  154,  153,
      329,  328,  223,  327,  326,  193,  162,  162,  162,  325,
      324,  156,  162,  162,  162,  323,  322,  156,  163,  163,

      162,  321,  320,  162,  224,  319,  318,  317,  316,  165,
      315,  314,  313,  166,  312,  165,  311,  310,  309,  166,
      308,  227,  307,  306,  305,  228,   56,   56,   56,   56,
       59,   59,   59,   59,   83,   83,   83,   83,   99,   99,
       99,   99,  149,  304,  149,  149,  151,  303,  151,  151,
      154,  154,  154,  154,  163,  163,  300,  163,  191,  191,
      191,  191,  222,  222,  222,  222,  226,  226,  226,  226,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  275,  274,  273,  272,  271,  270,  269,  268,

      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  221,  220,  219,  218,  217,
      216,  215,  214,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      186,  185,  178,  176,  175,  170,  169,  168,  167,  158,
      157,  150,  148,  147,  146,  145,  141,  137,  133,  132,
      121,  120,  119,  118,  117,  104,  103,  102,   97,  356,
       11,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356
    } ;

static yyconst short int yy_chk[653] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,   13,  365,   13,   28,   28,
      361,    3,    4,    5,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    9,    9,    9,   23,
       39,    9,   16,   16,   16,  353,   26,   16,   23,   24,
       26,   39,   24,   24,   39,    9,   26,   24,   24,   27,
       27,   40,   41,   63,    9,   63,    9,    9,  352,   16,
       47,   40,   41,    9,   41,   42,    9,    9,   79,    9,
       79,   42,    9,   10,   10,   10,  347,   47,   10,   45,
       47,   49,   71,   71,   27,   94,   45,   45,   66,   66,

       66,   94,   10,   66,   80,   49,   90,   49,   72,   72,
      344,   10,   80,   10,   10,   73,   73,   73,   90,   84,
       10,   84,  232,   10,   10,   66,   10,   71,   89,   10,
      232,   89,   91,   95,   95,  108,  108,   73,   73,   91,
      343,   96,   73,   96,   98,   98,   98,  114,  114,   98,
       99,   99,   99,  116,  116,   99,  101,  101,  101,  341,
      116,  101,  152,  267,  152,  116,  116,  116,  116,  116,
      116,   98,  139,  267,  153,  153,  153,   99,  139,  153,
      154,  154,  154,  101,  336,  154,  156,  156,  156,  159,
      159,  156,  177,  333,  177,  328,  327,  162,  162,  162,

      326,  153,  161,  161,  163,  163,  163,  154,  325,  161,
      164,  164,  164,  156,  161,  161,  161,  161,  161,  161,
      162,  165,  165,  165,  162,  323,  321,  163,  320,  318,
      317,  163,  316,  164,  166,  166,  166,  164,  180,  166,
      180,  191,  191,  191,  165,  180,  191,  180,  165,  192,
      192,  192,  314,  313,  192,  310,  309,  166,  193,  193,
      193,  166,  307,  193,  222,  222,  222,  306,  191,  222,
      223,  223,  223,  305,  304,  223,  192,  224,  224,  224,
      303,  301,  224,  300,  299,  193,  226,  226,  226,  298,
      297,  222,  227,  227,  227,  296,  295,  223,  228,  228,

      228,  293,  292,  228,  224,  288,  286,  284,  283,  226,
      281,  280,  279,  226,  278,  227,  277,  276,  274,  227,
      273,  228,  272,  271,  270,  228,  357,  357,  357,  357,
      358,  358,  358,  358,  359,  359,  359,  359,  360,  360,
      360,  360,  362,  269,  362,  362,  363,  268,  363,  363,
      364,  364,  364,  364,  366,  366,  266,  366,  367,  367,
      367,  367,  368,  368,  368,  368,  369,  369,  369,  369,
      265,  264,  263,  261,  260,  259,  257,  256,  255,  253,
      252,  250,  249,  244,  241,  240,  239,  238,  237,  235,
      234,  233,  231,  230,  220,  218,  217,  216,  215,  214,

      213,  212,  211,  209,  208,  206,  205,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  179,  178,  175,  174,
      173,  172,  171,  170,  169,  148,  146,  145,  144,  143,
      142,  141,  140,  138,  137,  136,  135,  133,  132,  131,
      130,  129,  128,  127,  125,  124,  123,  122,  121,  120,
       93,   92,   88,   82,   81,   78,   77,   75,   74,   70,
       67,   58,   55,   53,   51,   50,   48,   46,   44,   43,
       38,   37,   33,   32,   31,   22,   19,   18,   15,   11,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "stack.lex"
#define INITIAL 0
#line 2 "stack.lex"
/*=========================================================================
C-libraries and Token definitions
=========================================================================*/
#include <string.h> /* for strdup */
/*#include <stdlib.h> */ /* for atoi */
#include "token.h"
#include "stack_tab.h" /* for token definitions and yylval */
#include "lex_proto.h"
#include "sym_table.h"
#include "asm_streamer.h"

#define YY_INPUT(buf,result,max_size) { \
	int c = '*', n, d; \
	for ( n = 0; n < max_size && \
		     (c = pp_getc( p_config )) != EOF && c != '\n'; ++n ) \
		buf[n] = (char)(c); \
	if ( c == '\n' ) { \
        while((d = pp_getc( p_config )) == '\r' || d == '\n') { if( d=='\n' ) p_config->line++; }\
        if( d == EOF) {\
            pp_close( p_config);\
		    p_config = lp_pop_config();\
        } else {\
            pp_seek( p_config, -1, SEEK_CUR);\
		    buf[n++] = (char) c; \
        }\
	} \
	if ( c == EOF && pp_error(  p_config ) ) {\
		/*printf( "input in flex scanner failed\n" );*/ \
	}\
	if(p_config->show_assembly) {\
		as_info(_RECAST(uchar *, buf));	\
	}\
	if ( c == EOF) {\
		pp_close( p_config);\
		p_config = lp_pop_config();\
	}\
	result = n; \
	/*printf("%s\n", buf);*/\
	if(result<=0) result=YY_NULL; \
}


/*=========================================================================
TOKEN Definitions
=========================================================================*/
#define BLOCK_COMMENT_SECTION 1

#define LINE_COMMENT_SECTION 2

#define PREPROCESSOR_SECTION 3

#define ASSEMBLER_SECTION 4

/*=========================================================================
REGULAR EXPRESSIONS defining the tokens for the Simple language
=========================================================================*/
#line 684 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 59 "stack.lex"

#line 837 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 357 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 591 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 61 "stack.lex"
{ BEGIN(PREPROCESSOR_SECTION); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "stack.lex"
{ BEGIN(LINE_COMMENT_SECTION); } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "stack.lex"
{ /* eat up whitespace */ } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "stack.lex"
{ p_config->line++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "stack.lex"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "stack.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "stack.lex"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "stack.lex"

	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "stack.lex"

	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "stack.lex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "stack.lex"

	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "stack.lex"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "stack.lex"

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "stack.lex"

	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "stack.lex"

	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "stack.lex"

	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "stack.lex"

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "stack.lex"

	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "stack.lex"

	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "stack.lex"

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "stack.lex"

	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "stack.lex"

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK


case 24:
YY_RULE_SETUP
#line 87 "stack.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 88 "stack.lex"
{ /* eat comment in chunks */ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 89 "stack.lex"
{ /* eat the lone star */ }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 90 "stack.lex"
{ p_config->line++; }
	YY_BREAK


case 28:
YY_RULE_SETUP
#line 94 "stack.lex"
{ p_config->line++; BEGIN(INITIAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "stack.lex"
// eat comment in chunks
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "stack.lex"
// eat the lone star
	YY_BREAK


case 31:
YY_RULE_SETUP
#line 100 "stack.lex"
{ p_config->line++; lp_flush_token(); if(_lex_state != LEX_STATE_INVALID) BEGIN(INITIAL); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "stack.lex"
{ lp_flush_token(); if(_lex_state != LEX_STATE_INVALID) BEGIN(LINE_COMMENT_SECTION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "stack.lex"
{ /*lp_preprocessor_state(LEX_STATE_INCLUDE);*/ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_PRAGMA); 	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_DEFINE);  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_IFDEF); 	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_IF); 		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 108 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_ELSE); 	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 109 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_ENDIF); 	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "stack.lex"
{ BEGIN(ASSEMBLER_SECTION); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "stack.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "stack.lex"
{ 
		uchar buffer[256];
		uint16 length;
		memset(buffer, 0, 256);
		memcpy(buffer, yytext + 1, strlen(yytext) - 2);
		length = lp_unescape(buffer, buffer);
		lp_process_token(buffer, length);
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "stack.lex"
{ 
		uchar buffer[256];
		memset(buffer, 0, 256);
		memcpy(buffer, yytext + 1, strlen(yytext) - 2);
		lp_process_token(buffer, strlen((const char *)buffer));
	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "stack.lex"
{
		lp_process_token(_RECAST(uchar *, yytext), strlen(_RECAST(const char *, yytext)));
	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 129 "stack.lex"
{ 				
		char buffer[256];	
		memset(buffer, 0, 256);
		sprintf(buffer, "%i", lp_hex2integer(yytext + 2));
		lp_process_token((uchar *)buffer, strlen((const char *)buffer));
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 135 "stack.lex"
{
		lp_process_token(_RECAST(uchar *, yytext), strlen(yytext));
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 138 "stack.lex"
{ lp_push_opcode(LEX_OP_EQ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "stack.lex"
{ lp_push_opcode(LEX_OP_NEG); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 140 "stack.lex"
{ lp_push_opcode(LEX_OP_LT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 141 "stack.lex"
{ lp_push_opcode(LEX_OP_GT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 142 "stack.lex"
{ lp_push_opcode(LEX_OP_LTEQ); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 143 "stack.lex"
{ lp_push_opcode(LEX_OP_GTEQ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 144 "stack.lex"
{ lp_push_opcode(LEX_OP_OR); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 145 "stack.lex"
{ lp_push_opcode(LEX_OP_AND); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 146 "stack.lex"
{ /* ignore */ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 147 "stack.lex"
{ /* ignore */ }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 148 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 151 "stack.lex"
{ /* eat up whitespace */ } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 152 "stack.lex"
{ p_config->line++; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 153 "stack.lex"
{ /* eat up byte order mark */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 155 "stack.lex"
{ BEGIN(BLOCK_COMMENT_SECTION); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 156 "stack.lex"
{ BEGIN(PREPROCESSOR_SECTION); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 158 "stack.lex"
{ return S_ADDEQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 159 "stack.lex"
{ return S_SUBEQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 160 "stack.lex"
{ return S_ADDADD; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 161 "stack.lex"
{ return S_SUBSUB; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 162 "stack.lex"
{ return S_MULEQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 163 "stack.lex"
{ return S_DIVEQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 164 "stack.lex"
{ return S_MODEQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 166 "stack.lex"
{ return T_EQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 167 "stack.lex"
{ return T_AND; }	//type and
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 168 "stack.lex"
{ return T_OR; }	//type or
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 169 "stack.lex"
{ return T_NE; }	//type not equal
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 170 "stack.lex"
{ return L_CL; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 171 "stack.lex"
{ return R_CL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 172 "stack.lex"
{ return EOS; } 	//semicolon (end of statement)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 173 "stack.lex"
{ return EOC; } 	//colon (end of label)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 174 "stack.lex"
{ return L_BR; }	//left bracket
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 175 "stack.lex"
{ return R_BR; } 	//right bracket
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 176 "stack.lex"
{ return T_GT; }	//type greater than
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 177 "stack.lex"
{ return T_LT; }	//type less than
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 178 "stack.lex"
{ return T_GTEQ; }	//type greater than
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 179 "stack.lex"
{ return T_LTEQ; }	//type less than
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 180 "stack.lex"
{ return S_EQ; }	//type equal
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 181 "stack.lex"
{ return S_ADD; } 	
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 182 "stack.lex"
{ return S_SUB; } 	
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 183 "stack.lex"
{ return S_MUL; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 184 "stack.lex"
{ return S_DIV; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 185 "stack.lex"
{ return S_MOD; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 186 "stack.lex"
{ return L_SB; }	//left square bracket
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 187 "stack.lex"
{ return R_SB; } 	//right square bracket
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 188 "stack.lex"
{ return S_RNEXT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 189 "stack.lex"
{ return S_PDOT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 191 "stack.lex"
{ return P_VAR; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 192 "stack.lex"
{ return P_NEW; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 193 "stack.lex"
{ return P_HEX; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 194 "stack.lex"
{ return P_SIZEOF; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 196 "stack.lex"
{ return P_GOTO; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 197 "stack.lex"
{ return P_IF; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 198 "stack.lex"
{ return P_ELSE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 199 "stack.lex"
{ return P_WHILE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 200 "stack.lex"
{ return P_FUNCTION; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 201 "stack.lex"
{ return P_ALIAS; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 202 "stack.lex"
{ return P_EVENT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 203 "stack.lex"
{ return P_SWITCH; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 204 "stack.lex"
{ return P_CASE; } 
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 205 "stack.lex"
{ return P_DEFAULT; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 206 "stack.lex"
{ return P_BREAK; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 207 "stack.lex"
{ return P_FOR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 208 "stack.lex"
{ return P_DO; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 209 "stack.lex"
{ return P_CONTINUE; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 210 "stack.lex"
{ return P_RETURN; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 211 "stack.lex"
{ return P_PROTO; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 212 "stack.lex"
{ return P_EXTERN; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 213 "stack.lex"
{ return P_SYSCALL; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 215 "stack.lex"
{ return P_CLASS; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 216 "stack.lex"
{ return P_INTERFACE; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 217 "stack.lex"
{ return P_PACKAGE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 218 "stack.lex"
{ return P_IMPORT; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 219 "stack.lex"
{ return P_PUBLIC; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 220 "stack.lex"
{ return P_PRIVATE; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 221 "stack.lex"
{ return P_PROTECTED; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 223 "stack.lex"
{ 
	char buffer[256];
	uint16 length;
	memset(buffer, 0, 256);
	memcpy(buffer, yytext + 1, strlen(yytext) - 2);
	memset(yylval.bytes, 0, sizeof(yylval.bytes));
	length = lp_unescape(_RECAST(uchar *, yylval.bytes), _RECAST(uchar *, buffer));
	return CONSTANT; 
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 233 "stack.lex"
{ BEGIN(LINE_COMMENT_SECTION); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 235 "stack.lex"
{ 				
	char buffer[256];	
	memset(buffer, 0, 256);
	memcpy(buffer, yytext, strlen(yytext));
	memcpy((uchar *)(yylval.bytes), buffer, strlen(buffer) + 1);
	return CONSTANT; 
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 243 "stack.lex"
{ 				
	char buffer[256];	
	memset(buffer, 0, 256);
	memcpy(buffer, yytext, strlen(yytext));
	memcpy((uchar *)(yylval.bytes), buffer, strlen(buffer) + 1);
	return N_CONSTANT; 
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 251 "stack.lex"
{ 				
	char buffer[256];	
	memset(buffer, 0, 256);
	sprintf(buffer, "%i", lp_hex2integer(yytext + 2));
	memcpy((uchar *)(yylval.bytes), buffer, strlen(buffer) + 1);
	return CONSTANT; 
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 259 "stack.lex"
{	
	pp_const * pconst = NULL;
	symrec * var = NULL;
	char buffer[256];
	uint32 offset = 0;
	pconst = lp_select(_RECAST(uchar *, yytext));			/* select from preprocessor constants */
	if(pconst == NULL) {
		memset(buffer, 0, 256);
		memcpy(buffer, yytext, strlen(yytext));
		memcpy((uchar *)(yylval.bytes), buffer, strlen(buffer) + 1);
		return VARIABLE;
	} else {							/* preprocessor constant found */
		memset(buffer, 0, 256);
		memcpy(buffer, pconst->value, strlen(_RECAST(const char *, pconst->value)) + 1);
		memcpy(_RECAST(uchar *, yylval.bytes), buffer, strlen(_RECAST(const char *, buffer)) + 1);
		return CONSTANT;
	}	
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 278 "stack.lex"
{ return(yytext[0]); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 279 "stack.lex"
ECHO;
	YY_BREAK
#line 1647 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLOCK_COMMENT_SECTION):
case YY_STATE_EOF(LINE_COMMENT_SECTION):
case YY_STATE_EOF(PREPROCESSOR_SECTION):
case YY_STATE_EOF(ASSEMBLER_SECTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 357 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 357 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 356);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 279 "stack.lex"


int yywrap(void) { return -1; }

void yyinit(void) { 
	YY_FLUSH_BUFFER;
	BEGIN(INITIAL);	
}

/************************** End Scanner File *****************************/



